name: Terraform Staging CD

on:
  workflow_run:
    workflows: ["Terraform CD"]
    types:
      - completed

jobs:
  terraform:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment: # Set GitHub environment for this job
        name: staging

    env: # Set environment variable for Terraform to use
      ENVIRONMENT: staging

    defaults:
      run:
        working-directory: infra/envs/staging

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
              {
                "clientId": "${{ secrets.ARM_CLIENT_ID }}",
                "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
                "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
                "tenantId": "${{ secrets.ARM_TENANT_ID }}"
              }

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=staging.tfvars