name: Terraform Pipeline

on:
  pull_request:

  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:

  # PR PLAN ONLY
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    environment: dev
    env:
      ENVIRONMENT: dev

    defaults:
      run:
        working-directory: infra/envs/dev

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}"
            }
    

      - name: Terraform Init
        run: |
            terraform init \
            -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP }}" \
            -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
            -backend-config="key=${{ env.ENVIRONMENT }}.terraform.tfstate" \
            -backend-config="use_azuread_auth=true"
        
      
      - name: Terraform Plan
        run: terraform plan -no-color -var-file=dev.tfvars -out=tfplan

  # DEV (AUTO DEPLOY)
  dev:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    environment: dev

    env:
      ENVIRONMENT: dev

    defaults:
      run:
        working-directory: infra/envs/dev

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}"
            }

      - name: Terraform Init
        run: |
            terraform init \
            -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP }}" \
            -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT }}" \
            -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
            -backend-config="key=${{ env.ENVIRONMENT }}.terraform.tfstate" \
            -backend-config="use_azuread_auth=true"

      - name: Terraform Plan
        run: terraform plan -no-color -var-file=dev.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

  # STAGING (AUTO TRIGGER + APPROVAL)
  staging:
    if: github.event_name == 'push'
    needs: dev
    runs-on: ubuntu-latest

    environment: staging   # 👈 approval happens here

    env:
      ENVIRONMENT: staging

    defaults:
      run:
        working-directory: infra/envs/staging

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.ARM_CLIENT_ID }}",
              "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.ARM_TENANT_ID }}"
            }

      - name: Terraform Init
        run: terraform init \
          -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP }}" \
          -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT }}" \
          -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
          -backend-config="key=${{ env.ENVIRONMENT }}.terraform.tfstate" \
          -backend-config="use_azuread_auth=true"

      - name: Terraform Plan
        run: terraform plan -no-color -var-file=staging.tfvars -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

  # PROD (PROMOTION AFTER STAGING)
#   prod:
#     # if: github.event_name == 'push'
    # needs: staging
    # runs-on: ubuntu-latest

    # environment: prod   # 👈 stricter approval

    # env:
    #   ENVIRONMENT: prod

    # defaults:
    #   run:
    #     working-directory: infra/envs/prod

    # steps:
    #   - uses: actions/checkout@v4
    #   - uses: hashicorp/setup-terraform@v3

    #   - uses: azure/login@v2
    #     with:
    #       creds: |
    #         {
    #           "clientId": "${{ secrets.ARM_CLIENT_ID }}",
    #           "clientSecret": "${{ secrets.ARM_CLIENT_SECRET }}",
    #           "subscriptionId": "${{ secrets.ARM_SUBSCRIPTION_ID }}",
    #           "tenantId": "${{ secrets.ARM_TENANT_ID }}"
    #         }

    #   - name: Terraform Init
    #     run: terraform init \
    #       -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP }}" \
    #       -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT }}" \
    #       -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
    #       -backend-config="key=${{ env.ENVIRONMENT }}.terraform.tfstate" \
    #       -backend-config="use_azuread_auth=true"

    #   - name: Terraform Plan
    #     run: terraform plan -no-color -var-file=prod.tfvars -out=tfplan

    #   - name: Terraform Apply
    #     run: terraform apply -auto-approve tfplan